### PR TITLE
Use quantization info for parsing quantization style information

### LINKED ISSUE #23: Review and update QCD logic
Initial test results suggest something not complete, but needs some more investigation

### LINKED ISSUE #91: Debug and fix QCC (?) parsing
p0_13.j2k won't parse.

```
[2026-01-01T00:41:30Z ERROR jpc] unexpected marker type: 0x0900
Error: "error decoding jpc codestream unexpected marker Unknown Marker (0x0900) at byte offset 862
```

That looks like something is going wrong in the QCC parsing. Could be something earlier though.

### PR DESCRIPTION
**Pull request by Lanzaa**
* Add new decode_qcd unit tests
* Major changes to decode_qcd
* Change to using quantization info
* Update packet_marker_tests
* Update qcc struct to use quant info

Fixes #91 
Fixes #23

### CODE REVIEW

File: jpc/src/lib.rs [hunk 1]
```diff
@@ -1524,33 +1537,143 @@ impl CommentMarkerSegment {
...
+/// See ITU-T T.800(V4) or ISO/IEC 15444-1:2024 Section A.6.4
+#[derive(Debug)]
+pub struct QuantizationInfo {
+    pub guard_bits: u8, // 0..=7
+    pub style: QuantStyle,
+    values_bytes: Vec<u8>,
+}
+
+#[derive(Debug, PartialEq, Eq)]
+pub enum QuantStyle {
```
Comment (bradh) [inline jpc/src/lib.rs]: QuantizationStyle and NoQuantization as the first enum value would be better.

File: jpc/src/lib.rs [hunk 2]
```diff
@@ -1524,33 +1537,143 @@ impl CommentMarkerSegment {
...
+            QuantStyle::ScalarDerived => 1,
+            QuantStyle::ScalarExpounded => 2,
+            QuantStyle::Reserved(v) => v,
+        };
+        g + qs
+    }
 
-        // 000x xxxx to 111x xxxx, Number of guard bits: 0 to 7
-        let guard = u8::from_be(byte >> 5);
+    /// Grab the exponents for the quantization values
```
Comment (bradh) [inline jpc/src/lib.rs]: Would benefit from a spec reference, especially since I think this only applies for the reversible case. Possibly you intended to use the `SHIFT_BIG` version for the irreversible case?

File: jpc/src/lib.rs [hunk 3]
```diff
@@ -1648,11 +1767,7 @@ pub struct QuantizationComponentSegment {
     // Cqcc: The index of the component to which this marker segment relates.
     component_index: [u8; 2],
```
Comment (bradh) [inline jpc/src/lib.rs]: I think we should read these in and persist them as `u16`.  There is a TODO item for that. Can be a follow-up change though.

File: jpc/src/lib.rs [hunk 4]
```diff
@@ -2799,6 +2839,28 @@ impl ContiguousCodestream {
...
+                    | MarkerSymbol([0xff, 0x39])
+                    | MarkerSymbol([0xff, 0x3A])
+                    | MarkerSymbol([0xff, 0x3B])
+                    | MarkerSymbol([0xff, 0x3C])
+                    | MarkerSymbol([0xff, 0x3D])
+                    | MarkerSymbol([0xff, 0x3E])
+                    | MarkerSymbol([0xff, 0x3F]) => {
+                        // Reserved as marker only, not a segment
+                        info!("Skipping marker: {:?}", marker_type);
+                    }
```
Comment (bradh) [inline jpc/src/lib.rs]: This looks like a different change.

**Review by bradh — CHANGES_REQUESTED** [review]

File: jpc/src/lib.rs (hunk 3 above)
Comment (Lanzaa) [reply jpc/src/lib.rs]: Ok, created issue #96 to track the change.
