### PR TITLE
Fix COD coding style and precinct size extraction

### LINKED ISSUE #22: Correct handling of COD precinct sizes
The logic for `has_precinct_size()` is inverted.

### PR DESCRIPTION
**Pull request by iszak**
@bradh I think this fixes #22. The reserved detection for coding style is now broken.

### CODE REVIEW

File: jpc/src/lib.rs [hunk 1]
```diff
@@ -285,29 +285,30 @@ impl CodingStyleDefault {
     fn new(value: u8) -> Vec<CodingStyleDefault> {
         let mut coding_styles: Vec<CodingStyleDefault> = vec![];
 
-        if value & 0b_0000_0001 > 0 {
+        if value & 0b1001 == 0 {
```
Comment (bradh) [inline jpc/src/lib.rs]: I think we should only check the LSB here (and corresponding bits for SOP and EPH). There are uses of the higher bits in 15444-2 (see Table A.5) - they won't always be set to zero.

File: jpc/src/lib.rs [hunk 2]
```diff
@@ -285,29 +285,30 @@ impl CodingStyleDefault {
...
-            coding_styles.push(CodingStyleDefault::Reserved {
-                value: value >> 3 << 3,
-            });
-        }
+        // TODO
+        // if value != 0 {
+        //     coding_styles.push(CodingStyleDefault::Reserved {
+        //         value: value >> 3 << 3,
+        //     });
+        // }
```
Comment (bradh) [inline jpc/src/lib.rs]:
```suggestion
        // TODO: implement ISO/IEC 15444-2 Table A.5 extensions
```

File: jpc/src/lib.rs [hunk 3]
```diff
@@ -616,13 +617,18 @@ impl CodingStyleParameters {
         TransformationFilter::new(self.transformation)
     }
 
-    pub fn has_precinct_size(&self) -> bool {
-        self.coding_style[0] << 7 >> 7 != 0b_0000_0000
+    pub fn has_defined_precinct_size(&self) -> bool {
+        self.coding_style[0] & 0b1001 == 1
```
Comment (bradh) [inline jpc/src/lib.rs]:
```suggestion
        self.coding_style[0] & 0b0000_0001 == 0b0000_0001
```

File: jpc/tests/packet_marker_tests.rs [hunk 4]
```diff
@@ -85,9 +93,15 @@ fn test_eph() {
         TransformationFilter::Reversible
     );
 
-    // TODO: fix this
-    // assert_eq!(cod.coding_style_parameters().has_precinct_size(), true);
-    // assert!(cod.coding_style_parameters().precinct_sizes().is_some());
+    assert_eq!(
```
[the remark this answers is not in the document]
Comment (iszak) [reply jpc/tests/packet_marker_tests.rs]: `cargo clippy --fix` doesn't detect/fix it for me.

**Review by bradh — APPROVED** [review]
I think we might need a different approach when (or if) we support Part 2 extensions, but looks good for now.
